ALTER TABLE pf_epic_version ADD COLUMN content_version BIGINT;
UPDATE pf_epic_version SET content_version=version;
ALTER TABLE pf_epic_version ADD COLUMN impact_json TEXT NOT NULL DEFAULT '{}';
CREATE TABLE pf_epic_review (
    id VARCHAR(36) PRIMARY KEY,
    review_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
    epic_id VARCHAR(36) NOT NULL REFERENCES pf_epic(id),
    content_version BIGINT NOT NULL,
    policy_version BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('PRODUCT_OWNER','ARCHITECT')),
    actor_id VARCHAR(100) NOT NULL,
    decision VARCHAR(30) NOT NULL,
    reason TEXT NOT NULL,
    automatic BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL UNIQUE,
    fingerprint VARCHAR(64) NOT NULL
);
CREATE INDEX pf_epic_review_version_idx ON pf_epic_review(epic_id, content_version, policy_version);
