-- One identity sequence across every product. UUIDs and foreign keys remain unchanged.
ALTER TABLE pf_epic ADD COLUMN epic_number BIGINT GENERATED BY DEFAULT AS IDENTITY;
-- Backfill existing epics deterministically; identity has already advanced past these rows.
UPDATE pf_epic SET epic_number = (
    SELECT COUNT(*) FROM pf_epic older
    WHERE older.created_at < pf_epic.created_at
       OR (older.created_at = pf_epic.created_at AND older.id <= pf_epic.id)
);
ALTER TABLE pf_epic ADD CONSTRAINT uq_pf_epic_number UNIQUE (epic_number);
ALTER TABLE pf_epic ADD CONSTRAINT ck_pf_epic_number CHECK (epic_number > 0);
