-- Overleg ("meeting"): een meerturige chatconversatie tussen de producteigenaar en de AI die een
-- specifiek product draait. Een product kan zelf ook aangeven dat het overleg wil (pending vlag +
-- onderwerpen op product_definition hieronder); de 7-dagengate daarop wordt afgedwongen door
-- nl.vdzon.productfactory.meeting.api.MeetingCatalog, niet vertrouwd op het eigen oordeel van de AI.
create table meeting (
    id varchar(120) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    sequence_number integer not null,
    initiator varchar(20) not null,
    status varchar(20) not null default 'OPEN',
    requested_topics text,
    outcome_summary text,
    created_at timestamp with time zone not null default current_timestamp,
    closed_at timestamp with time zone,
    unique (product_slug, sequence_number)
);

create table meeting_message (
    id bigint generated by default as identity primary key,
    meeting_id varchar(120) not null references meeting(id),
    product_slug varchar(80) not null references product_definition(slug),
    sender varchar(10) not null,
    content text not null,
    created_at timestamp with time zone not null default current_timestamp
);

create index meeting_product_status_idx on meeting(product_slug, status);
create index meeting_product_closed_idx on meeting(product_slug, closed_at);
create index meeting_message_meeting_idx on meeting_message(meeting_id, created_at);

-- Pending "ik wil overleg"-vlag die een product zelf zet (via de SUMMARY-rol aan het eind van een
-- cyclus, zie ShadowIterationEngine.generateSummary). meeting_requested_topics is een JSON-array-
-- string; het product moet zijn eigen onderwerpen dus zelf onthouden totdat de vlag wordt opgepakt
-- doordat er een nieuw overleg gestart wordt.
alter table product_definition add column meeting_requested_at timestamp with time zone;
alter table product_definition add column meeting_requested_topics text;
