-- Roadmap: een door de Product Manager-rol (fase 3, nog niet in deze migratie) bijgehouden lijst
-- thema's/epics per product, met een eigen prioriteit en status die over meerdere productcycli heen
-- blijft bestaan — in tegenstelling tot de losse "focus" van een enkele shadow-iteratie. Bewust
-- gescheiden van shadow_iteration: een thema leeft langer dan één cyclus en wordt niet per se elke
-- cyclus aangeraakt.
create table roadmap_theme (
    id varchar(120) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    sequence_number integer not null,
    title varchar(240) not null,
    description text not null,
    priority varchar(20) not null,
    status varchar(20) not null default 'OPEN',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    closed_at timestamp with time zone,
    unique (product_slug, sequence_number)
);

-- Losstaand van de thema's: vastgestelde onderzoeksfeiten met een eenmalig antwoord (bv. "is dit
-- archief zonder token te benaderen") die nooit opnieuw onderzocht hoeven te worden. Bewust een
-- aparte tabel, niet een status op roadmap_theme: een afgehandelde vraag is geen thema dat "af" is,
-- maar een feit dat nooit een thema was.
create table roadmap_settled_question (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    content text not null,
    created_at timestamp with time zone not null default current_timestamp
);

create index roadmap_theme_product_status_idx on roadmap_theme(product_slug, status);
create index roadmap_settled_question_product_idx on roadmap_settled_question(product_slug);
