create table product_definition (
    slug varchar(80) primary key,
    name varchar(200) not null,
    mission text not null,
    guardrails text not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table story_candidate (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    title varchar(240) not null,
    description text not null,
    status varchar(32) not null default 'INTERNAL',
    created_at timestamp with time zone not null default current_timestamp
);

create table workspace_publication (
    run_id varchar(120) primary key,
    product_slug varchar(80) not null,
    artifact_path varchar(500) not null,
    content_hash varchar(64) not null,
    status varchar(32) not null,
    pull_request_url varchar(1000),
    commit_sha varchar(64),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table agent_run (
    run_id varchar(120) primary key,
    product_slug varchar(80) not null,
    task_type varchar(80) not null,
    status varchar(32) not null,
    result_reference varchar(1000),
    started_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone
);
