-- Eerste fundament voor versiebeheer van productgeheugen. Bestaande geheugenregels blijven
-- onveranderlijk; een vervanging is een nieuwe regel die naar zijn voorganger verwijst en een
-- intrekking is een afzonderlijk append-only record.
alter table product_memory add column supersedes_id bigint references product_memory(id);
alter table product_memory add column change_reason text;
alter table product_memory add column created_by varchar(120) not null default 'system';

create unique index product_memory_one_successor_idx on product_memory(supersedes_id);

create table product_memory_retraction (
    id bigint generated by default as identity primary key,
    memory_id bigint not null unique references product_memory(id),
    product_slug varchar(80) not null references product_definition(slug),
    reason text not null,
    created_by varchar(120) not null,
    created_at timestamp with time zone not null default current_timestamp
);

-- Een AI-antwoord houdt zelf bij welke bronnen zijn geraadpleegd en welke memorywijzigingen door
-- het systeem werkelijk zijn toegepast. Dit maakt het overleg controleerbaar in het dashboard.
alter table meeting_message add column consulted_sources text;
alter table meeting_message add column memory_changes text;
