create table product_bug (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug) on delete cascade,
    title varchar(240) not null,
    description text not null,
    reproduction_steps text not null,
    expected_result text not null,
    actual_result text not null,
    priority varchar(2) not null,
    status varchar(32) not null default 'OPEN',
    source_type varchar(32) not null,
    source_id varchar(120),
    fingerprint varchar(64) not null,
    occurrence_count integer not null default 1,
    linked_candidate_id bigint references story_candidate(id),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    last_verified_at timestamp with time zone,
    resolved_at timestamp with time zone,
    constraint product_bug_priority_check check (priority in ('P0', 'P1', 'P2', 'P3')),
    constraint product_bug_status_check check (status in ('OPEN', 'IN_PROGRESS', 'READY_FOR_VERIFICATION', 'RESOLVED', 'OBSOLETE')),
    unique (product_slug, fingerprint)
);

create index product_bug_product_priority_status_idx
    on product_bug(product_slug, status, priority, updated_at);

alter table story_candidate add column bug_id bigint references product_bug(id);

create table test_session (
    id varchar(120) primary key,
    product_slug varchar(80) not null references product_definition(slug) on delete cascade,
    sequence_number integer not null,
    status varchar(32) not null,
    summary text,
    error_message text,
    tested_areas integer not null default 0,
    bugs_created integer not null default 0,
    bugs_updated integer not null default 0,
    bugs_resolved integer not null default 0,
    workspace_run_id varchar(120),
    workspace_pull_request_url varchar(1000),
    workspace_commit_sha varchar(64),
    created_at timestamp with time zone not null default current_timestamp,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    unique (product_slug, sequence_number)
);

create index test_session_product_status_idx on test_session(product_slug, status);

create table product_test_schedule (
    product_slug varchar(80) not null references product_definition(slug) on delete cascade,
    day_of_week varchar(9) not null,
    time_of_day time not null,
    primary key (product_slug, day_of_week, time_of_day),
    constraint product_test_schedule_day_check check (
        day_of_week in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

-- Iedere bestaande productscope krijgt twee zichtbare regressiemomenten per week.
insert into product_test_schedule(product_slug, day_of_week, time_of_day)
select slug, 'TUESDAY', time '10:00:00' from product_definition;

insert into product_test_schedule(product_slug, day_of_week, time_of_day)
select slug, 'FRIDAY', time '10:00:00' from product_definition;
