-- Living vision v2 is additive: legacy sessions and APIs remain valid.
alter table product_definition add column roadmap_process_version varchar(40) not null default 'legacy-v1';
alter table roadmap_session add column process_version varchar(40) not null default 'legacy-v1';

create table roadmap_idea (
    id varchar(140) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    idea_key varchar(100) not null,
    status varchar(32) not null,
    current_version integer not null,
    promise text not null,
    primary_audience text not null,
    need text not null,
    origin varchar(80) not null,
    first_session_id varchar(120),
    status_reason text,
    evidence text,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    unique(product_slug, idea_key)
);

create table roadmap_idea_version (
    id bigint generated by default as identity primary key,
    idea_id varchar(140) not null references roadmap_idea(id),
    product_slug varchar(80) not null references product_definition(slug),
    version integer not null,
    promise text not null,
    primary_audience text not null,
    need text not null,
    details_json text not null,
    change_reason text not null,
    created_by_session_id varchar(120),
    created_by_role varchar(80) not null,
    created_at timestamp with time zone not null default current_timestamp,
    unique(idea_id, version)
);

create table roadmap_inspiration (
    id varchar(140) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    session_id varchar(120) not null references roadmap_session(id),
    producer_role varchar(80) not null,
    source_url varchar(2000) not null,
    title varchar(500) not null,
    accessed_at timestamp with time zone not null,
    observation text not null,
    interpretation text not null,
    relevance text not null,
    limitations text,
    confidence integer not null,
    screenshot_media_id varchar(100) references product_media(id),
    rights_note text,
    created_at timestamp with time zone not null default current_timestamp
);

create table roadmap_ux_concept (
    id varchar(140) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    concept_key varchar(100) not null,
    idea_key varchar(100) not null,
    status varchar(32) not null,
    current_version integer not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    unique(product_slug, concept_key),
    foreign key(product_slug, idea_key) references roadmap_idea(product_slug, idea_key)
);

create table roadmap_ux_concept_version (
    id bigint generated by default as identity primary key,
    concept_id varchar(140) not null references roadmap_ux_concept(id),
    product_slug varchar(80) not null references product_definition(slug),
    version integer not null,
    idea_version integer not null,
    viewport varchar(20) not null,
    flow_position integer not null,
    user_goal text not null,
    interaction text not null,
    content_text text not null,
    states_json text not null,
    decisions_json text not null,
    assumptions_json text not null,
    open_questions_json text not null,
    review text,
    created_by_session_id varchar(120),
    created_at timestamp with time zone not null default current_timestamp,
    unique(concept_id, version, viewport, flow_position)
);

create table roadmap_ux_concept_asset (
    concept_version_id bigint not null references roadmap_ux_concept_version(id),
    media_id varchar(100) not null references product_media(id),
    position integer not null,
    primary key(concept_version_id, media_id)
);

create table roadmap_research_result (
    id varchar(140) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    session_id varchar(120) not null references roadmap_session(id),
    idea_key varchar(100) not null,
    concept_key varchar(100),
    capability_key varchar(120),
    research_type varchar(60) not null,
    question text not null,
    evidence text not null,
    sources_json text not null,
    limitations text not null,
    confidence integer not null,
    status varchar(40) not null,
    conclusion text not null,
    recommended_next_step text not null,
    dependencies_json text not null,
    created_at timestamp with time zone not null default current_timestamp,
    foreign key(product_slug, idea_key) references roadmap_idea(product_slug, idea_key)
);

create table roadmap_session_step (
    id varchar(220) primary key,
    session_id varchar(120) not null references roadmap_session(id),
    product_slug varchar(80) not null references product_definition(slug),
    role varchar(80) not null,
    scope_key varchar(120) not null,
    status varchar(32) not null,
    process_version varchar(40) not null,
    required_step boolean not null,
    attempt integer not null default 1,
    provider varchar(80),
    model varchar(120),
    input_artifact_ids_json text not null default '[]',
    output_artifact_ids_json text not null default '[]',
    handoff_json text,
    error_message text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    unique(session_id, role, scope_key, attempt)
);

create table roadmap_session_step_dependency (
    step_id varchar(220) not null references roadmap_session_step(id),
    depends_on_step_id varchar(220) not null references roadmap_session_step(id),
    primary key(step_id, depends_on_step_id)
);

create table roadmap_activation (
    id varchar(140) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    session_id varchar(120) not null references roadmap_session(id),
    vision_id varchar(120) references roadmap_future_vision(id),
    changelog text not null,
    activated_at timestamp with time zone not null default current_timestamp,
    unique(session_id)
);

create index roadmap_idea_product_status_idx on roadmap_idea(product_slug, status);
create index roadmap_inspiration_product_session_idx on roadmap_inspiration(product_slug, session_id);
create index roadmap_concept_product_idea_idx on roadmap_ux_concept(product_slug, idea_key);
create index roadmap_research_product_idea_idx on roadmap_research_result(product_slug, idea_key);
create index roadmap_step_ready_idx on roadmap_session_step(session_id, status);
