alter table product_definition add column id varchar(80);
update product_definition set id = concat('product-', slug) where id is null;
alter table product_definition alter column id set not null;
create unique index product_definition_id_uq on product_definition(id);

alter table product_definition add column description text not null default '';
alter table product_definition add column software_factory_project_key varchar(120) not null default '';
alter table product_definition add column target_repository_name varchar(240) not null default '';
alter table product_definition add column workspace_directory varchar(240) not null default '';
alter table product_definition add column workspace_ownership varchar(32) not null default 'owner';
alter table product_definition add column live_url varchar(1000);
alter table product_definition add column preview_url_pattern varchar(1000);
alter table product_definition add column status varchar(32) not null default 'draft';
alter table product_definition add column development_mode varchar(32) not null default 'manual';
alter table product_definition add column iteration_schedule varchar(120) not null default '0 3 * * *';
alter table product_definition add column timezone varchar(80) not null default 'Europe/Amsterdam';
alter table product_definition add column max_stories_per_cycle integer not null default 3;
alter table product_definition add column wip_limit integer not null default 1;
alter table product_definition add column ai_provider varchar(80) not null default 'codex';
alter table product_definition add column ai_model varchar(120) not null default 'default';
alter table product_definition add column daily_budget_cents integer not null default 0;
alter table product_definition add column monthly_budget_cents integer not null default 0;
alter table product_definition add column escalation_policy text not null default '';
alter table product_definition add column source_rules text not null default '';
alter table product_definition add column privacy_rules text not null default '';
alter table product_definition add column accessibility_rules text not null default '';
alter table product_definition add column quality_rules text not null default '';
alter table product_definition add column updated_at timestamp with time zone not null default current_timestamp;

create table product_allowed_write_path (
    product_slug varchar(80) not null references product_definition(slug),
    relative_path varchar(240) not null,
    primary key (product_slug, relative_path)
);

create table product_research (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    title varchar(240) not null,
    content text not null,
    source_url varchar(1000),
    created_at timestamp with time zone not null default current_timestamp
);

create table product_memory (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    title varchar(240) not null,
    content text not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table product_decision (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    title varchar(240) not null,
    content text not null,
    created_at timestamp with time zone not null default current_timestamp
);

alter table workspace_publication add constraint workspace_publication_product_fk
    foreign key (product_slug) references product_definition(slug);
alter table agent_run add constraint agent_run_product_fk
    foreign key (product_slug) references product_definition(slug);

insert into product_definition (
    id, slug, name, mission, guardrails, description, software_factory_project_key,
    target_repository_name, workspace_directory, workspace_ownership, live_url,
    preview_url_pattern, status, development_mode, iteration_schedule, timezone,
    max_stories_per_cycle, wip_limit, ai_provider, ai_model, daily_budget_cents,
    monthly_budget_cents, escalation_policy, source_rules, privacy_rules,
    accessibility_rules, quality_rules
) values (
    'pf-product-hkh-v1', 'hkh', 'Historische Kring Heemskerk',
    'De geschiedenis van Heemskerk toegankelijk, betekenisvol en beleefbaar maken door lokale bronnen te verbinden met historische collecties daarbuiten.',
    'De eigenaar houdt de regie over productontwikkeling en publicatie.',
    'Handmatig ontwikkeld vergelijkingsproduct voor de HKH-app.', 'hkh', 'hkh',
    'products/hkh', 'owner', 'https://hkh.vdzonsoftware.nl',
    'https://hkh-pr-{number}.vdzonsoftware.nl', 'active', 'observe-only',
    '0 3 * * *', 'Europe/Amsterdam', 3, 1, 'codex', 'default', 0, 0,
    'Benader de eigenaar alleen voor handelingen die niet door de factory uitgevoerd kunnen worden.',
    'Maak herkomst, onzekerheid en tegenstrijdige bronnen zichtbaar.',
    'Sla geen persoonsgegevens op zonder duidelijk doel en passende grondslag.',
    'Ontwerpen moeten bruikbaar zijn met toetsenbord en schermlezer en voldoende contrast hebben.',
    'Werk in kleine toetsbare stappen en maak aannames expliciet.'
);

insert into product_definition (
    id, slug, name, mission, guardrails, description, software_factory_project_key,
    target_repository_name, workspace_directory, workspace_ownership, live_url,
    preview_url_pattern, status, development_mode, iteration_schedule, timezone,
    max_stories_per_cycle, wip_limit, ai_provider, ai_model, daily_budget_cents,
    monthly_budget_cents, escalation_policy, source_rules, privacy_rules,
    accessibility_rules, quality_rules
) values (
    'pf-product-hkh-autopilot-v1', 'hkh-autopilot', 'HKH Autopilot',
    'De geschiedenis van Heemskerk toegankelijk, betekenisvol en beleefbaar maken door lokale bronnen te verbinden met historische collecties daarbuiten.',
    'Onderzoek autonoom, onderbouw beslissingen en publiceer alleen binnen de geregistreerde productworkspace.',
    'Autonoom ontwikkeld vergelijkingsproduct voor de HKH-app.', 'hkh-autopilot',
    'hkh-autopilot', 'products/hkh-autopilot', 'product-factory',
    'https://hkh-autopilot.vdzonsoftware.nl',
    'https://hkh-autopilot-pr-{number}.vdzonsoftware.nl', 'active', 'autonomous',
    '0 3 * * *', 'Europe/Amsterdam', 3, 1, 'codex', 'default', 0, 0,
    'Benader de eigenaar alleen voor accounts, toestemmingen of andere onvermijdelijke menselijke handelingen.',
    'Maak herkomst, onzekerheid en tegenstrijdige bronnen zichtbaar.',
    'Sla geen persoonsgegevens op zonder duidelijk doel en passende grondslag.',
    'Ontwerpen moeten bruikbaar zijn met toetsenbord en schermlezer en voldoende contrast hebben.',
    'Werk in kleine toetsbare stappen en maak aannames expliciet.'
);

insert into product_allowed_write_path(product_slug, relative_path) values
    ('hkh-autopilot', 'research'),
    ('hkh-autopilot', 'product-memory'),
    ('hkh-autopilot', 'decisions'),
    ('hkh-autopilot', 'ux'),
    ('hkh-autopilot', 'roadmap'),
    ('hkh-autopilot', 'stories');
