create table shadow_iteration (
    id varchar(120) primary key,
    product_slug varchar(80) not null references product_definition(slug),
    sequence_number integer not null,
    focus text not null,
    status varchar(32) not null,
    current_agent_role varchar(40),
    critic_verdict varchar(20),
    workspace_run_id varchar(120),
    workspace_pull_request_url varchar(1000),
    workspace_commit_sha varchar(64),
    error_message text,
    created_at timestamp with time zone not null default current_timestamp,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    unique (product_slug, sequence_number)
);

create table shadow_iteration_step (
    id bigint generated by default as identity primary key,
    iteration_id varchar(120) not null references shadow_iteration(id),
    product_slug varchar(80) not null references product_definition(slug),
    role varchar(40) not null,
    attempt integer not null default 1,
    run_id varchar(120) not null unique,
    status varchar(32) not null,
    output_json text,
    error_message text,
    started_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone,
    unique (iteration_id, role, attempt)
);

create table shadow_iteration_artifact (
    iteration_id varchar(120) not null references shadow_iteration(id),
    product_slug varchar(80) not null references product_definition(slug),
    artifact_type varchar(40) not null,
    content_json text not null,
    created_at timestamp with time zone not null default current_timestamp,
    primary key (iteration_id, artifact_type)
);

create table research_source (
    id bigint generated by default as identity primary key,
    iteration_id varchar(120) not null references shadow_iteration(id),
    product_slug varchar(80) not null references product_definition(slug),
    url varchar(1500) not null,
    consulted_on date not null,
    rights_indication varchar(500) not null,
    rationale text not null,
    unique (iteration_id, url)
);

create table product_ux (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    iteration_id varchar(120) not null references shadow_iteration(id),
    title varchar(240) not null,
    content text not null,
    created_at timestamp with time zone not null default current_timestamp
);

alter table story_candidate add column iteration_id varchar(120) references shadow_iteration(id);
alter table story_candidate add column fingerprint varchar(64);
alter table story_candidate add column acceptance_criteria text;
alter table story_candidate add column critic_status varchar(32);
alter table story_candidate add column critic_reason text;
alter table story_candidate add column duplicate_of_id bigint references story_candidate(id);

create index story_candidate_product_fingerprint_idx on story_candidate(product_slug, fingerprint);
create index shadow_iteration_product_status_idx on shadow_iteration(product_slug, status);
