alter table shadow_iteration add column mode varchar(20) not null default 'shadow';

create table story_delivery (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    candidate_id bigint not null unique references story_candidate(id),
    iteration_id varchar(120) not null references shadow_iteration(id),
    workspace_run_id varchar(120) not null,
    workspace_commit_sha varchar(64) not null,
    artifact_path varchar(500) not null,
    idempotency_key varchar(180) not null unique,
    external_story_key varchar(80) unique,
    status varchar(32) not null,
    remote_phase varchar(80),
    error_message text,
    created_at timestamp with time zone not null default current_timestamp,
    delivered_at timestamp with time zone,
    completed_at timestamp with time zone,
    last_reconciled_at timestamp with time zone,
    evaluation_workspace_run_id varchar(120),
    evaluated_at timestamp with time zone
);

create index story_delivery_product_status_idx on story_delivery(product_slug, status);

create table story_question (
    id bigint generated by default as identity primary key,
    delivery_id bigint not null references story_delivery(id),
    external_target_key varchar(80) not null,
    phase varchar(80) not null,
    question text not null,
    status varchar(32) not null,
    answer text,
    agent_run_id varchar(160),
    error_message text,
    created_at timestamp with time zone not null default current_timestamp,
    answered_at timestamp with time zone,
    unique (delivery_id, external_target_key, phase)
);

create table human_action (
    id bigint generated by default as identity primary key,
    product_slug varchar(80) not null references product_definition(slug),
    delivery_id bigint references story_delivery(id),
    question_id bigint references story_question(id),
    category varchar(80) not null,
    title varchar(240) not null,
    reason text not null,
    instructions text,
    status varchar(32) not null default 'OPEN',
    created_at timestamp with time zone not null default current_timestamp,
    completed_at timestamp with time zone
);

create index human_action_product_status_idx on human_action(product_slug, status);
