apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-factory-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          envFrom:
            - configMapRef:
                name: product-factory-config
            - secretRef:
                name: product-factory-secrets
          env:
            - name: PF_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: product-factory-config
                  key: PF_DB_URL
            - name: PF_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: product-factory-config
                  key: PF_DB_USERNAME
