apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-factory
resources:
- ../../base
- configmap.yaml
- database.yaml
- sealed-secret-product-factory.yaml
- ../../database
patches:
- path: backend-secret-patch.yaml
images:
- digest: sha256:ebf0170a00f1da0098f36fa14ec07d14b091d54ee12deccd3194f1a1dab11fff
  name: ghcr.io/robbertvdzon/product-factory-backend
  newName: ghcr.io/robbertvdzon/product-factory-backend
- digest: sha256:6d89dec6fdcc77b25155c552efaad59851b5d0f82c139a6071d36cf05fba36ca
  name: ghcr.io/robbertvdzon/product-factory-frontend
  newName: ghcr.io/robbertvdzon/product-factory-frontend
