apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-factory
resources:
- ../../base
- configmap.yaml
- database.yaml
- sealed-secret-product-factory.yaml
- ../../database
patches:
- path: backend-secret-patch.yaml
images:
- digest: sha256:6b464d023be1e444f289b5e5ffe554faef8ce033dbabe72b192a02b4f56e6ad7
  name: ghcr.io/robbertvdzon/product-factory-backend
  newName: ghcr.io/robbertvdzon/product-factory-backend
- digest: sha256:a4d87d665eaf494e025b8a3e5deda6fa6294d172d2037d7ff7be28dc50a18936
  name: ghcr.io/robbertvdzon/product-factory-frontend
  newName: ghcr.io/robbertvdzon/product-factory-frontend
