apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: product-factory
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-local-path-scc
  namespace: product-factory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:local-path-postgresql
subjects:
  - kind: ServiceAccount
    name: postgres
    namespace: product-factory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: product-factory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
