apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-factory-backend
spec:
  template:
    spec:
      securityContext:
        seLinuxOptions: null
      volumes:
      - name: ai-artifacts
        persistentVolumeClaim: null
        emptyDir:
          sizeLimit: 1Gi
