---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: product-factory-preview-runtime
spec:
  encryptedData:
    PF_AGENT_RUNTIME_TEST_CONTROL_TOKEN: AgAlU+399T40TKhr71+F+7oh2zv6YJfOJ8YnkPlWcUOKImORCdqO7XNGguBkbPAxluMrkAX3AcjUoPJPPmGzxYxXSWKoyXcZub1Gjk8EeVZGsVVwE7HrcpLspY0yhY4N0rO75Z/omgZsh/Py/jwHQpQKS8NgkrNSO4SpPa7IqNTZyZshRhGjJud4m2KZ32kiRELRflGQA26ZtVLIqaaDy/Q/po19htGq8kEvsFpYTt6pC18wrVmcGLtqL9kTA1pzPoqCaqWIzd7AobDbiiRrM2vS/zG4xXkm4K8XXfpAFcvfeqoGoh0//8264DCojamGfw80+MXAdqQhpM/3QonV62w24kBlLFcTjKi2Gg3FdolgsimoDRYRL/8JezA6jAf+6MU1gl78MZZ8qEBz/Sde0Y16RHDhJzVn1do4HnhigrUfOP0w39cPR0CG+WJcMJ9M6AAU8Jtg8V/npQtDPwJPy1mPAr9En+cMGs/9ueKWB1fmobjjuWN+qeNld6p3d55fMlAbKXCdBW1kyjzkLYrhLDSM0QwKgpJMv8jdbQIc5xeqdWdOQ6M0DHUJyFTCX464FFmSWL3MnoR3iHtWY7hd+TXae3JTvYshTrZcE2268N2x3eu5MDJ9iQNwnG9brastVMi7heBBR7P87Sckmeaad/j9MhdjDl+Xnhn5FRyyLzJ05mlCB8SSSBHTCociQeHEsfMjrDJ4yDFQUgtDDun9Jc40hcj3iZkFRTzAj3aV7lHIPl1kcP/+IlrfJ2EXbOINglCkQpmHc9FnFVNZzSxty0cC
    PF_AGENT_RUNTIME_TOKEN: AgB2j2rMEdVgiutIqwMGU2EteYWANiAD5hSxSvCfDopkgLkeqQylvsLst4ATjXR1sNKEBXSLNRFa/sw0gT9nST/vMTqgFnYTdIQyxnZIJMng6zdx13GH0aq6pR8L/5NtcttGVsYU5WiPR2YC4VZQ/ssIlYdlR63K58BoW2GdcRdsm5dFJKAMPArkRROJqAx0qDrdZIZUpPMwHH/rLDpM1z2UD7Zmyr7A1x4ljf+Qg6M2D3hd0nyCx5KAV1nITrNFUsWJTEzjbD3EWN6g8iDT3/0p1zmuhj0J3gCBHXkdBaRBcSVY4hE9fqqDZZnPDR/RnNFSmkVFmZ6iDm+bwN7JrWi1P2ZdZMFrj26PQ9Bt6tDgfaZr6UxKlQF7JfLBH1UUviJHF5uXDP57BilDslYJcWrqoPjcnyTthO+H0ZXUDe/hrMbIjlQhLE7f7QjBGs0AjbNDI/dwWl8SegClQ76rMKFVAt+jXpyIaBbAp45w70bPhgilgkcCgazgEoXgdvkfWbFHdm3LUOTCuU3RqAAStVl0FdoLfM6ujzLf1OwsStijrHPVtHE3vw0Ve8+70FKJhmOxMPVA94Cuwknt+pfc4FA6faby+5mwdHiOfSty1a40gCsgm8bO9QzcCsTiFtJs1zRNQil09SEQ3hDcAAGYsiIC/xHZWLaHAOCyrQbeJ4v735BluVHWjpzDV58o6Vwui6NGg1uAzdWV0umH70m5brfJMHYuUNkIC/zhdnYgBnqcdkMq7BoSZWApUSHaIt5SYb41Xc5JJ0RRlMRnd86Wc084
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: product-factory-preview-runtime
