apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-factory-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          envFrom:
            - configMapRef:
                name: product-factory-config
            - secretRef:
                name: product-factory-runtime-secrets
