apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-factory-acceptance
resources:
- ../../base
- configmap.yaml
- sealed-secret-agent-runtime.yaml
- sealed-secret-ai-access.yaml
- sealed-central-postgres.yaml
patches:
- path: routes-patch.yaml
- path: backend-runtime-secret-patch.yaml
- path: agent-access-patch.yaml
- path: backend-memory.yaml
- path: product-factory-frontend-memory.yaml
- path: central-postgres-patch.yaml
images:
- digest: sha256:824e53207b7fe5ea15b769406ba9f5f012da44114c651f880132c54bf11e98d2
  name: ghcr.io/robbertvdzon/product-factory-backend
  newName: ghcr.io/robbertvdzon/product-factory-backend
- digest: sha256:0f4535d2d50acdf8eb7a2232b382920b98a3237e908262653641cddf1b24a6c0
  name: ghcr.io/robbertvdzon/product-factory-frontend
  newName: ghcr.io/robbertvdzon/product-factory-frontend
