apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-factory-acceptance
resources:
- ../../base
- configmap.yaml
- sealed-secret-agent-runtime.yaml
patches:
- path: routes-patch.yaml
- path: backend-runtime-secret-patch.yaml
images:
- digest: sha256:846a191784bee7b4d2123575c5d77072190010c3bfd0181f0a8ebc502d364e07
  name: ghcr.io/robbertvdzon/product-factory-backend
  newName: ghcr.io/robbertvdzon/product-factory-backend
- digest: sha256:2d259df046c003fb3ffb137ff4f0d4db67465af84421ff9fa3674d211f01da11
  name: ghcr.io/robbertvdzon/product-factory-frontend
  newName: ghcr.io/robbertvdzon/product-factory-frontend
